manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/bobobo1618/zephyr/tree/fix-oled   # https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
