manifest:
  remotes:
    - name: bobobo1618   # zmkfirmware
      url-base: https://github.com/bobobo1618/zephyr/tree/fix-oled   # https://github.com/zmkfirmware
  projects:
    - name: zephyr   # zmk
      remote: bobobo1618   # zmkfirmware
      revision: fix-oled   # main
      import: app/west.yml
  self:
    path: config
